### ISSUE TITLE
Align all action columns to the right of table

### ISSUE THREAD

**Issue by DennisGarding** [swDennis/FossilCatalog#23]
Align all action columns to the right of table

**Comment by DennisGarding** [comment]
```FossilListTableActionColumn.js:20 Uncaught TypeError: Cannot read properties of null (reading 'offsetWidth')
    at FossilListTableActionColumn._calculateActionColumnWidth (FossilListTableActionColumn.js:20:53)
    at new FossilListTableActionColumn (FossilListTableActionColumn.js:12:14)
    at list:91:21
    at NodeList.forEach (<anonymous>)
    at Ajax.successCallback (list:90:30)
    at xhttp.onreadystatechange (Ajax.js:61:24)
_calculateActionColumnWidth @ FossilListTableActionColumn.js:20
FossilListTableActionColumn @ FossilListTableActionColumn.js:12
xhttp.onreadystatechange @ Ajax.js:61
XMLHttpRequest.send (async)
execute @ Ajax.js:36
```
